Repository fourhe/backend, pull requests merged in 2024-01, with the labels that each got.

#15 편지 삭제 및 복구 기능 추가
  src/main/java/com/letter2sea/be/exception/type/LetterExceptionType.java
  src/main/java/com/letter2sea/be/letter/controller/MailBoxController.java
  src/main/java/com/letter2sea/be/letter/domain/Letter.java
  src/main/java/com/letter2sea/be/letter/repository/LetterRepository.java
  src/main/java/com/letter2sea/be/letter/service/LetterService.java
  src/main/java/com/letter2sea/be/mailbox/MailBoxRepository.java
  src/main/java/com/letter2sea/be/member/Member.java
  src/main/java/com/letter2sea/be/trash/TrashController.java
  src/main/java/com/letter2sea/be/trash/TrashRepository.java
  src/main/java/com/letter2sea/be/trash/TrashService.java
  src/main/java/com/letter2sea/be/trash/domain/Trash.java
  src/main/java/com/letter2sea/be/trash/dto/TrashDetailResponse.java
  src/main/java/com/letter2sea/be/trash/dto/TrashListResponse.java
Labels: ✨ feat

#19 메뉴 인포 기능 및 감사인사 기능 구현
  src/main/java/com/letter2sea/be/exception/type/MailBoxExceptionType.java
  src/main/java/com/letter2sea/be/letter/controller/MailBoxController.java
  src/main/java/com/letter2sea/be/letter/domain/Letter.java
  src/main/java/com/letter2sea/be/letter/repository/LetterRepository.java
  src/main/java/com/letter2sea/be/letter/service/LetterService.java
  src/main/java/com/letter2sea/be/mailbox/MailBoxRepository.java
  src/main/java/com/letter2sea/be/mailbox/domain/MailBox.java
  src/main/java/com/letter2sea/be/member/Member.java
  src/main/java/com/letter2sea/be/menu/controller/MenuController.java
  src/main/java/com/letter2sea/be/menu/dto/MenuInfoResponse.java
  src/main/java/com/letter2sea/be/menu/service/MenuService.java
  src/test/java/com/letter2sea/be/BeApplicationTests.java
Labels: 🔧 fix

#20 NewHasReply 기능 구현 및 리스트 페이지네이션
  src/main/java/com/letter2sea/be/letter/controller/LetterController.java
  src/main/java/com/letter2sea/be/letter/controller/MailBoxController.java
  src/main/java/com/letter2sea/be/letter/dto/response/LetterListResponse.java
  src/main/java/com/letter2sea/be/letter/dto/response/LetterPaginatedResponse.java
  src/main/java/com/letter2sea/be/letter/repository/LetterRepository.java
  src/main/java/com/letter2sea/be/letter/service/LetterService.java
  src/main/java/com/letter2sea/be/mailbox/MailBoxRepository.java
  src/main/java/com/letter2sea/be/trash/TrashController.java
  src/main/java/com/letter2sea/be/trash/TrashRepository.java
  src/main/java/com/letter2sea/be/trash/TrashService.java
  src/main/java/com/letter2sea/be/trash/dto/TrashPaginatedResponse.java
Labels: ✨ feat, 👩🏻‍💻 hanse, 🧑🏻‍💻 phill
