Repository fourhe/backend, pull requests merged in 2024-02, with the labels that each got.

#22 메뉴 Info 반환 값 수정
  src/main/java/com/letter2sea/be/auth/service/LoginService.java
  src/main/java/com/letter2sea/be/member/Member.java
  src/main/java/com/letter2sea/be/member/dto/MemberUpdateRequest.java
  src/main/java/com/letter2sea/be/member/service/MemberService.java
  src/main/java/com/letter2sea/be/menu/dto/MenuInfoResponse.java
  src/main/java/com/letter2sea/be/menu/service/MenuService.java
  src/main/java/com/letter2sea/be/trash/TrashRepository.java
  src/main/resources/application.yml
Labels: ✨ feat, 🔧 fix

#25 :sparkles: TrashList pagination 기능 수정
  src/main/java/com/letter2sea/be/exception/type/CommonExceptionType.java
  src/main/java/com/letter2sea/be/trash/TrashController.java
  src/main/java/com/letter2sea/be/trash/TrashRepository.java
  src/main/java/com/letter2sea/be/trash/TrashService.java
Labels: ✨ feat, 👩🏻‍💻 hanse, 🧑🏻‍💻 phill, ⚒ refactor

#26 회원 탈퇴 기능 추가
  src/main/java/com/letter2sea/be/exception/type/LetterExceptionType.java
  src/main/java/com/letter2sea/be/letter/repository/LetterRepository.java
  src/main/java/com/letter2sea/be/letter/service/LetterService.java
  src/main/java/com/letter2sea/be/member/Member.java
  src/main/java/com/letter2sea/be/member/controller/MemberController.java
  src/main/java/com/letter2sea/be/member/service/MemberService.java
Labels: ✨ feat, 🧑🏻‍💻 phill

#28 답장 리스트 조회 시 감사 여부도 표시하는 기능 추가
  src/main/java/com/letter2sea/be/letter/controller/MailBoxController.java
  src/main/java/com/letter2sea/be/letter/dto/response/ReplyListResponse.java
  src/main/java/com/letter2sea/be/letter/service/LetterService.java
Labels: ✨ feat, 🔧 fix

#30 답장을 받으면 유저에게 이메일로 알림을 보낸다.
  build.gradle
  src/main/java/com/letter2sea/be/auth/controller/OAuthController.java
  src/main/java/com/letter2sea/be/auth/service/LoginService.java
  src/main/java/com/letter2sea/be/common/config/AwsSesConfig.java
  src/main/java/com/letter2sea/be/common/config/TemplateConfig.java
  src/main/java/com/letter2sea/be/common/util/MailSender.java
  src/main/java/com/letter2sea/be/letter/service/LetterService.java
  src/main/resources/application.yml
  src/main/resources/templates/index.html
Labels: ✨ feat
